{{- if .Values.functions.patchAndTransform.enabled }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: {{ .Values.functions.patchAndTransform.package }}
{{- end }}
{{- if .Values.functions.environmentConfigs.enabled }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-environment-configs
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: {{ .Values.functions.environmentConfigs.package }}
{{- end }}
