apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /keycloak/health
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.global.ingress_name | default "platform" }}
spec:
  ingressClassName: platform
  rules:
    - host: {{ .Values.global.ingress_domain_name }}
      http:
        paths:
          - path: /keycloak
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
