{{- if .Values.tempSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-clients
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  ARGO_WORKFLOWS_CLIENT_ID: "argo-workflows"
  ARGO_WORKFLOWS_CLIENT_SECRET: "temp-secret-{{ randAlphaNum 32 }}"
  BACKSTAGE_CLIENT_ID: "backstage"
  BACKSTAGE_CLIENT_SECRET: "temp-secret-{{ randAlphaNum 32 }}"
  ARGOCD_CLIENT_ID: "argocd"
  ARGOCD_CLIENT_SECRET: "temp-secret-{{ randAlphaNum 32 }}"
  ARGOCD_SESSION_TOKEN: "temp-token-{{ randAlphaNum 32 }}"
{{- end }}
