apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{values.appname}}-cicd-provisioner
  namespace: ${{values.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{values.appname}}-cicd-provisioner-binding
  namespace: ${{values.namespace}}
subjects:
- kind: ServiceAccount
  name: ${{values.appname}}-cicd-provisioner
  namespace: ${{values.namespace}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# IAM Role using ACK
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: "${{values.appname}}-cicd-provisioner-iam-role"
  namespace: ${{values.namespace}}
spec:
  name: "${{values.appname}}-cicd-provisioner-iam-role"
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "pods.eks.amazonaws.com"
          },
          "Action": [
            "sts:AssumeRole",
            "sts:TagSession"
          ]
        }
      ]
    }
---
# IAM Policy using ACK
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: "${{values.appname}}-cicd-provisioner-ecr-access-policy"
  namespace: ${{values.namespace}}
spec:
  name: "${{values.appname}}-cicd-provisioner-ecr-access-policy"
  description: "ECR Access Policy for CICD"
  policyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "ecr:GetAuthorizationToken",
            "ecr:GetRepositoryPolicy",
            "ecr:DescribeRepositories",
            "ecr:CreateRepository",
            "ecr:BatchCheckLayerAvailability",
            "ecr:GetDownloadUrlForLayer",
            "ecr:ListImages",
            "ecr:DescribeImages",
            "ecr:BatchGetImage",
            "ecr:GetLifecyclePolicy",
            "ecr:GetLifecyclePolicyPreview",
            "ecr:ListTagsForResource",
            "ecr:DescribeImageScanFindings",
            "ecr:InitiateLayerUpload",
            "ecr:UploadLayerPart",
            "ecr:CompleteLayerUpload",
            "ecr:PutImage"
          ],
          "Resource": "*"
        }
      ]
    }
---
# PodIdentityAssociation using ACK
apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  name: "${{values.appname}}-cicd-provisioner-podidentity"
  namespace: ${{values.namespace}}
spec:
  clusterName: "modern-engineering"
  namespace: "${{values.namespace}}"
  serviceAccount: "${{values.appname}}-cicd-provisioner"
  roleARN: "arn:aws:iam::${{values.aws_account_id}}:role/${{values.appname}}-cicd-provisioner-iam-role"
