apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis-ha-haproxy
  labels:
    app: redis-ha-proxy
    release: argocd
    app.kubernetes.io/name: redis-ha-haproxy
spec:
  replicas: 1 # Typically scaled out for HA
  template:
    spec:
      containers:
      - name: haproxy
        image: public.ecr.aws/docker/library/haproxy:3.3.5-alpine # Example image
        args: ["-f", "/usr/local/etc/haproxy/haproxy.cfg"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
      volumes:
      - name: redis-config
        configMap:
          name: argocd-redis-ha-haproxy-config
