apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: aws-s3-bucket-test-mikhail312331
  namespace: default
spec:
  components:
    - name: test-mikhail312331
      type: s3-bucket-ack
      properties:
        name: test-mikhail312331
        region: us-west-2
