apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: git-credentials
  namespace: java-app-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: git-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      engineVersion: v2
      mergePolicy: Replace
      data:
        repoURL: ${GITLAB_URL}/${GIT_USERNAME}/java.git
        username: ${GIT_USERNAME}
        password: '{{.GIT_PASSWORD}}'
  data:
    - secretKey: GIT_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: peeks-hub/secrets
        metadataPolicy: None
        property: git_token