apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: java-app-kargo
  annotations:
    kargo.akuity.io/color: green
    kargo.akuity.io/auto-promotion: "false"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: java-app
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: update-image
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: java-app-kargo
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: java-app
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: update-image