apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates Kubernetes Spark Job
  name: argo-workflows-spark-job
  title: Basic Argo Workflow with a Spark Job
spec:
  owner: guest
  type: service
  parameters:
    - title: Configuration Options
      required:
        - name
      properties:
        name:
          type: string
          description: name of this application
        mainApplicationFile:
          type: string
          default: 'local:///opt/spark/examples/jars/spark-examples_2.12-3.1.3.jar'
          description: Path to the main application file
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - id: template
      name: Generating component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{parameters.name}}
          repoUrl: ${{ steps['fetchSystem'].output.entity.spec.hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab
      input:
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.hostname }}?repo=${{parameters.name}}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: argocd:create-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.name}}
        argoInstance: in-cluster
        projectName: default
        repoUrl: https://${{ steps['fetchSystem'].output.entity.spec.hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
