# EKS Pod Identity Association for External Secrets Operator
# Created by Crossplane on Kind during bootstrap, then adopted by
# Crossplane on the hub via crossplane.io/external-name annotation
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: eso-pod-identity
  annotations:
    crossplane.io/external-name: a-yctoakuwrwza5tbao
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    clusterName: hub
    namespace: external-secrets
    serviceAccount: external-secrets-sa
    roleArnSelector:
      matchLabels:
        platform.gitops.io/role: eso-pod-identity
    region: us-west-2
  providerConfigRef:
    name: default
