# EKS Pod Identity Association for AWS Load Balancer Controller
# Created by Crossplane on Kind during bootstrap, then adopted by
# Crossplane on the hub via crossplane.io/external-name annotation
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: lbc-pod-identity
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    clusterName: hub
    namespace: kube-system
    serviceAccount: aws-load-balancer-controller-sa
    roleArnRef:
      name: lbc-pod-identity-role
    region: us-west-2
  providerConfigRef:
    name: default
