apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: modernengg-custom-templates
  description: Modern Engineering Backstage Custom Templates
spec:
  targets:
    - ./ddb-table/template.yaml