{{- if not (eq (toString .Values.createIdentities) "false") }}
{{- range $name, $provider := .Values.providers }}
{{- if and $provider.version $provider.serviceAccount $provider.roleName }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{ $name }}-provider-role
  annotations:
    crossplane.io/external-name: {{ $provider.roleName }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
  labels:
    platform.gitops.io/role: {{ $name }}-provider
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [{
          "Effect": "Allow",
          "Principal": {"Service": "pods.eks.amazonaws.com"},
          "Action": ["sts:AssumeRole", "sts:TagSession"]
        }]
      }
    tags:
      managed-by: crossplane
      purpose: {{ $name }}-provider
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
{{- range $name, $provider := .Values.providers }}
{{- if and $provider.version $provider.serviceAccount $provider.roleName }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ $name }}-provider-admin-attachment
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  forProvider:
    policyArn: "arn:aws:iam::aws:policy/AdministratorAccess"
    roleRef:
      name: {{ $name }}-provider-role
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
{{- range $name, $provider := .Values.providers }}
{{- if and $provider.version $provider.serviceAccount $provider.roleName }}
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: {{ $name }}-provider-pod-identity
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  forProvider:
    clusterName: {{ $.Values.aws.clusterName }}
    namespace: {{ $.Values.namespace }}
    serviceAccount: {{ $provider.serviceAccount }}
    roleArnSelector:
      matchLabels:
        platform.gitops.io/role: {{ $name }}-provider
    region: {{ $.Values.aws.region }}
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
{{- end }}
