{{- if .Values.providerConfig.enabled }}
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.providerConfig.name | default "default" }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  credentials:
    source: PodIdentity
{{- end }}
{{- range $name, $provider := .Values.providers }}
{{- if and $provider.version $provider.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $provider.serviceAccount }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ $name }}-drc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: {{ $provider.serviceAccount }}
          containers:
          - name: package-runtime
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
{{- end }}
{{- end }}
