{{- if .Values.providers.family.version }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-aws
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:{{ .Values.providers.family.version }}
  runtimeConfigRef:
    name: iam-drc
{{- end }}
{{- if .Values.providers.iam.version }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:{{ .Values.providers.iam.version }}
  runtimeConfigRef:
    name: iam-drc
{{- end }}
{{- if .Values.providers.ec2.version }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:{{ .Values.providers.ec2.version }}
  runtimeConfigRef:
    name: ec2-drc
{{- end }}
{{- if .Values.providers.eks.version }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-eks
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-eks:{{ .Values.providers.eks.version }}
  runtimeConfigRef:
    name: eks-drc
{{- end }}
{{- if .Values.providers.s3.version }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-s3:{{ .Values.providers.s3.version }}
  runtimeConfigRef:
    name: s3-drc
{{- end }}
{{- if .Values.providers.dynamodb.version }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-dynamodb
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-dynamodb:{{ .Values.providers.dynamodb.version }}
  runtimeConfigRef:
    name: dynamodb-drc
{{- end }}
{{- if .Values.providers.rds.version }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-rds
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-rds:{{ .Values.providers.rds.version }}
  runtimeConfigRef:
    name: rds-drc
{{- end }}
