apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://<DNS_NAME>/gitea/giteaAdmin/argocd-example-apps.git
    targetRevision: HEAD
    path: .
  destination:
    name: dev-cluster
    namespace: guestbook
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true