apiVersion: v1
kind: Secret
metadata:
  name: sample-cluster-argo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: dev-cluster
  server: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.gr7.us-west-2.eks.amazonaws.com
  config: |
    {
      "bearerToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
      }
    }
