{{- if eq .Values.mode "direct" }}
{{- $clusterName := required "clusterName is required" .Values.clusterName -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $clusterName }}
  namespace: argocd
  annotations:
    addonsRepoURL: {{ .Values.hub.addonsRepoURL | quote }}
    addonsRepoRevision: {{ .Values.hub.addonsRepoRevision | quote }}
    addonsRepoBasepath: {{ .Values.hub.addonsRepoBasepath | quote }}
    fleetRepoURL: {{ .Values.hub.fleetRepoURL | quote }}
    fleetRepoRevision: {{ .Values.hub.fleetRepoRevision | quote }}
    fleetRepoBasepath: {{ .Values.hub.fleetRepoBasepath | quote }}
    aws_region: {{ .Values.region | quote }}
    aws_account_id: {{ .Values.hub.accountId | quote }}
    aws_cluster_name: {{ $clusterName | quote }}
    ingress_domain_name: {{ .Values.hub.domain | quote }}
    resource_prefix: {{ .Values.hub.resourcePrefix | quote }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- range $addon, $enabled := .Values.enabledAddons }}
    {{- if $enabled }}
    enable_{{ $addon }}: 'true'
    {{- end }}
    {{- end }}
stringData:
  name: {{ $clusterName }}
  server: arn:aws:eks:{{ .Values.region }}:{{ .Values.hub.accountId }}:cluster/{{ $clusterName }}
  config: '{"tlsClientConfig":{"insecure":false}}'
{{- end }}
