# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: s3bucket.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    s3.awsblueprints.io/configuration: standard
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XObjectStorage
  mode: Pipeline
  pipeline:
    - step: s3-bucket
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: bucket
            base:
              apiVersion: s3.aws.upbound.io/v1beta2
              kind: Bucket
              spec:
                forProvider:
                  region: us-west-2
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
              - type: ToCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: status.bucketName
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.arn
                toFieldPath: status.bucketArn
              - fromFieldPath: metadata.uid
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-bucket"
              - fromFieldPath: spec.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
            connectionDetails:
              - name: bucket-name
                type: FromFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
              - name: region
                type: FromValue
                value: us-west-2
          - name: bucket-public-access-block
            base:
              apiVersion: s3.aws.upbound.io/v1beta1
              kind: BucketPublicAccessBlock
              spec:
                forProvider:
                  bucketSelector:
                    matchControllerRef: true
                  blockPublicPolicy: true
                  restrictPublicBuckets: true
                  region: us-west-2
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
          - name: bucket-ownership
            base:
              apiVersion: s3.aws.upbound.io/v1beta2
              kind: BucketOwnershipControls
              spec:
                forProvider:
                  bucketSelector:
                    matchControllerRef: true
                  rule:
                    objectOwnership: BucketOwnerEnforced
                  region: us-west-2
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
          - name: bucket-sse
            base:
              apiVersion: s3.aws.upbound.io/v1beta2
              kind: BucketServerSideEncryptionConfiguration
              spec:
                forProvider:
                  bucketSelector:
                    matchControllerRef: true
                  rule:
                    - applyServerSideEncryptionByDefault:
                        sseAlgorithm: AES256
                  region: us-west-2
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
