apiVersion: kro.run/v1alpha1
kind: AppmodService
metadata:
  name: progressive-app
  namespace: team-java
spec:
  image: argoproj/rollouts-demo:yellow
  image_name: rollout-demo
  replicas: 2
  port: 8080
  targetPort: 8080
  serviceAccount: progressive-service-account
  clusterName: peeks-spoke-dev
  env:
    - name: APP_ENV
      value: "PRODUCTION"
  components:
    dynamodb:
      enabled: false
  ingress:
    enabled: true
    path: /progressive
    rewrite: true
