apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ack-dynamodb-{{.metadata.name}}
  namespace: argocd
  labels:
    app.kubernetes.io/name: ack-dynamodb
    app.kubernetes.io/instance: ack-dynamodb
    app.kubernetes.io/part-of: ack-dynamodb
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: '{{.metadata.annotations.addons_repo_url}}'
    path: gitops/addons/default/addons/ack-dynamodb
    targetRevision: '{{.metadata.annotations.addons_repo_revision}}'
  destination:
    server: '{{.metadata.annotations.aws_cluster_endpoint}}'
    namespace: ack-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
      limit: 10
