apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Set up an API Gateway that forwards requests to an SQS queue for buffering.
  name: apigw-sqs-terraform
  title: API Gateway SQS Terraform Template
spec:
  owner: guest
  type: service
  parameters:
    - properties:
        tfVars:
          title: Terraform variables
          properties:
            name:
              title: Name for the build
              type: string
            aws_region:
              description: AWS Region
              type: string
          required:
            - name
            - aws_region
          type: object
        adminRoleName:
          description: Name of the role to give the administrative rights
          title: Admin role name
          type: string
        namespace:
          default: flux-system
          title: Existing namespace to create this resource
          type: string
      title: Configuration options
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - action: fetch:template
      id: fetch-base
      input:
        url: ./template-apigw-sqs-terraform/
        values:
          adminRoleName: ${{parameters.adminRoleName}}
          name: ${{parameters.tfVars.name}}
          namespace: ${{parameters.namespace}}
          tfVars: ${{parameters.tfVars}}
      name: Fetch Base
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab
      input:
        # Hard coded value for this demo purposes only.
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}?repo=${{parameters.tfVars.name}}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: argocd:create-app
      input:
        appName: ${{parameters.tfVars.name}}
        appNamespace: ${{parameters.namespace}}
        argoInstance: in-cluster
        projectName: default
        # necessary until we generate our own cert
        repoUrl: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.tfVars.name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}