apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.table_name}}
  description: DynamoDB table ${{values.table_name}}
  annotations:
    argocd/app-name: ${{values.table_name}}
spec:
  type: service
  lifecycle: production
  owner: user:guest
