apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ddb-table-${{values.table_name}}
  description: DynamoDB Table for ${{ values.table_name }}
  annotations:
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    argocd/app-name: ${{values.table_name | dump}}
spec:
  type: ddb-table
  lifecycle: experimental
  owner: guest
  system: ${{values.table_name | dump}}