apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-bucket-template-crossplane
  title: S3 Bucket Template Crosspane
  description: Create S3 bucket using OAM and CrossPlane
spec:
  owner: guest
  type: service
  parameters:
    - title: Provide S3 Bucket Information
      required:
        - bucket_name
        - environment
        - region
      properties:
        bucket_name:
          title: Bucket Name
          type: string
          description: Name of the S3 bucket
        environment:
          title: Environment
          type: string
          description: The environment (e.g., dev, prod)
          enum: ['dev', 'prod']
        provider:
          title: Provider
          type: string
          description: Provider Configuration
          default: default
        region:
          title: Region
          type: string
          description: AWS region for the S3 bucket
          default: us-west-2
        namespace:
          default: default
          title: Existing namespace to create this resource
          type: string
        configuration:
          default: standard
          title: Configuration of your S3 Bucket
          type: string
          enum: ['standard', 'intelligent-tiering']
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          provider: ${{ parameters.provider }}
          bucket_name: ${{ parameters.bucket_name }}
          configuration: ${{ parameters.configuration }}
          namespace: ${{ parameters.namespace }}
          environment: ${{ parameters.environment }}
          region: ${{ parameters.region }}
          repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab
      input:
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}?repo=${{parameters.bucket_name}}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: argocd:create-app
      input:
        appName: ${{parameters.bucket_name}}
        appNamespace: default
        argoInstance: in-cluster
        projectName: default
        repoUrl: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.bucket_name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
    - id: template-output
      name: Template Output
      action: debug:log
      input:
        listWorkspace: true
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
