apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-bucket-template-crossplane
  title: S3 Bucket Template Crosspane
  description: Create S3 bucket using OAM and CrossPlane
spec:
  owner: guest
  type: service
  parameters:
    - title: Provide S3 Bucket Information
      required:
        - bucket_name
        - environment
        - region
      properties:
        bucket_name:
          title: Bucket Name
          type: string
          description: Name of the S3 bucket
        environment:
          title: Environment
          type: string
          description: The environment (e.g., dev, prod)
          enum: ['dev', 'prod']
        provider:
          title: Provider
          type: string
          description: Provider Configuration
          default: default
        region:
          title: Region
          type: string
          description: AWS region for the S3 bucket
          default: us-west-2
        namespace:
          default: default
          title: Existing namespace to create this resource
          type: string
        configuration:
          default: standard
          title: Configuration of your S3 Bucket
          type: string
          enum: ['standard', 'intelligent-tiering']
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          provider: ${{ parameters.provider }}
          bucket_name: ${{ parameters.bucket_name }}
          configuration: ${{ parameters.configuration }}
          namespace: ${{ parameters.namespace }}
          environment: ${{ parameters.environment }}
          region: ${{ parameters.region }}
          repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab
      input:
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}?repo=${{parameters.bucket_name}}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        defaultBranch: main
        gitTimeout: 120
        useCustomGit: true
    - id: create-argocd-project
      name: Create ArgoCD Project
      action: kube:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: AppProject
          metadata:
            name: ${{parameters.bucket_name}}-project
            namespace: argocd
          spec:
            description: Project for ${{parameters.bucket_name}} S3 bucket
            sourceNamespaces:
            - argocd
            sourceRepos:
            - https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.bucket_name}}.git
            destinations:
            - namespace: ${{parameters.namespace}}
              name: ${{ steps['fetchSystem'].output.entity.spec.hub_cluster_name }}
            clusterResourceWhitelist:
            - group: '*'
              kind: '*'
            namespaceResourceWhitelist:
            - group: '*'
              kind: '*'
            orphanedResources:
              ignore:
              - kind: Bucket
    - id: create-argocd-app
      name: Create ArgoCD App
      action: kube:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{parameters.bucket_name}}
            namespace: argocd
            labels:
              backstage-name: ${{parameters.bucket_name}}
            finalizers:
            - resources-finalizer.argocd.argoproj.io
          spec:
            project: ${{parameters.bucket_name}}-project
            destination:
              namespace: ${{parameters.namespace}}
              name: ${{ steps['fetchSystem'].output.entity.spec.hub_cluster_name }}
            source:
              repoURL: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.bucket_name}}.git
              targetRevision: HEAD
              path: manifests
            syncPolicy:
              automated:
                allowEmpty: true
                prune: false
                selfHeal: true
              retry:
                backoff:
                  duration: 5s
                  factor: 2
                  maxDuration: 5m
                limit: 10
              syncOptions:
              - CreateNamespace=false
              - FailOnSharedResource=true
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.bucket_name}}/-/blob/main
        catalogInfoPath: "/catalog-info.yaml"
    - id: template-output
      name: Template Output
      action: debug:log
      input:
        listWorkspace: true
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
