{{- if .Values.spokeScrapers }}
{{- range $clusterName, $cluster := .Values.spokeScrapers }}
{{- if $cluster.clusterArn }}
---
apiVersion: amp.aws.upbound.io/v1beta1
kind: Scraper
metadata:
  name: {{ $.Values.resourcePrefix }}-scraper-{{ $clusterName }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    region: {{ $.Values.aws.region }}
    alias: {{ $.Values.resourcePrefix }}-{{ $clusterName }}
    source:
      - eks:
          - clusterArn: {{ $cluster.clusterArn }}
            subnetIds:
              {{- range (splitList "," $cluster.subnetIds) }}
              - {{ . | trim }}
              {{- end }}
            securityGroupIds:
              {{- range (splitList "," $cluster.securityGroupIds) }}
              - {{ . | trim }}
              {{- end }}
    destination:
      - amp:
          - workspaceArnRef:
              name: {{ $.Values.resourcePrefix }}-amp
    scrapeConfiguration: |
      global:
        scrape_interval: {{ $.Values.scraper.scrapeInterval }}
        scrape_timeout: {{ $.Values.scraper.scrapeTimeout }}
        external_labels:
          cluster: {{ $clusterName }}
          region: {{ $.Values.aws.region }}
          account_id: {{ $.Values.aws.accountId }}
      scrape_configs:
        - job_name: kubernetes-apiservers
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - action: keep
              regex: default;kubernetes;https
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_service_name
                - __meta_kubernetes_endpoint_port_name
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
        - job_name: kubernetes-nodes-cadvisor
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - replacement: kubernetes.default.svc:443
              target_label: __address__
            - regex: (.+)
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
              source_labels:
                - __meta_kubernetes_node_name
              target_label: __metrics_path__
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
        - job_name: kubernetes-service-endpoints
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - action: keep
              regex: "true"
              source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
                - __meta_kubernetes_service_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
                - __address__
                - __meta_kubernetes_service_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_service_name
              target_label: kubernetes_name
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - action: keep
              regex: "true"
              source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
                - __address__
                - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: kubernetes_pod_name
            - action: drop
              regex: Pending|Succeeded|Failed|Completed
              source_labels:
                - __meta_kubernetes_pod_phase
        - job_name: kube-state-metrics
          honor_labels: true
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - kube-prometheus-stack
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
              action: keep
              regex: kube-state-metrics
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
        - job_name: node-exporter
          honor_labels: true
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - kube-prometheus-stack
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              action: keep
              regex: prometheus-node-exporter
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
{{- end }}
