# Spoke dev clusters get their own ESO pod identity provisioned by
# Crossplane on the hub (chart default is false; opt in here).
identities:
  eso:
    enabled: true
  # Crossplane providers on spoke need Pod Identity so they can
  # create/manage AWS resources (IAM roles, policy attachments, etc.).
  # These associations are created by the hub's Crossplane targeting the spoke.
  crossplane-iam:
    enabled: true
    roleName: CrossplaneIAMProviderRole
    namespace: crossplane-system
    serviceAccount: provider-aws-iam
    tags:
      managed-by: crossplane
      purpose: crossplane-iam-provider
    policy:
      name: CrossplaneIAMProviderPolicy
      document: |
        {
          "Version": "2012-10-17",
          "Statement": [{"Effect": "Allow","Action": "*","Resource": "*"}]
        }
  crossplane-ec2:
    enabled: true
    roleName: CrossplaneEC2ProviderRole
    namespace: crossplane-system
    serviceAccount: provider-aws-ec2
    tags:
      managed-by: crossplane
      purpose: crossplane-ec2-provider
    policy:
      name: CrossplaneEC2ProviderPolicy
      document: |
        {
          "Version": "2012-10-17",
          "Statement": [{"Effect": "Allow","Action": "*","Resource": "*"}]
        }
  crossplane-amp:
    enabled: true
    roleName: CrossplaneAMPProviderRole
    namespace: crossplane-system
    serviceAccount: provider-aws-amp
    tags:
      managed-by: crossplane
      purpose: crossplane-amp-provider
    policy:
      name: CrossplaneAMPProviderPolicy
      document: |
        {
          "Version": "2012-10-17",
          "Statement": [{"Effect": "Allow","Action": "*","Resource": "*"}]
        }
  crossplane-grafana:
    enabled: true
    roleName: CrossplaneGrafanaProviderRole
    namespace: crossplane-system
    serviceAccount: provider-aws-grafana
    tags:
      managed-by: crossplane
      purpose: crossplane-grafana-provider
    policy:
      name: CrossplaneGrafanaProviderPolicy
      document: |
        {
          "Version": "2012-10-17",
          "Statement": [{"Effect": "Allow","Action": "*","Resource": "*"}]
        }
