apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-credentials
  namespace: ${{values.namespace}}
spec:
  secretStoreRef:
    name: gitea
    kind: ClusterSecretStore
  refreshInterval: "0"
  target:
    name: gitea-credentials
  data:
    - secretKey: GITEA_USERNAME
      remoteRef:
        key: gitea-credential
        property: username
    - secretKey: GIT_PASSWORD
      remoteRef:
        key: gitea-credential
        property: password
    - secretKey: GITEA_TOKEN
      remoteRef:
        key: gitea-credential
        property: token