apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: "1.9.0"
    helm:
      releaseName: karpenter
      valuesObject:
        settings:
          clusterName: __CLUSTER_NAME__
          interruptionQueue: __CLUSTER_NAME__-karpenter
        replicas: 2
        serviceAccount:
          name: karpenter
        tolerations:
          - key: role
            operator: Equal
            value: system
            effect: NoSchedule
        nodeSelector:
          role: system
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
