{{- range $name, $identity := .Values.identities }}
{{- if not (eq (toString $identity.enabled) "false") }}
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: {{ $name }}-pod-identity
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  forProvider:
    clusterName: {{ $.Values.aws.clusterName }}
    namespace: {{ $identity.namespace }}
    serviceAccount: {{ $identity.serviceAccount }}
    roleArnSelector:
      matchLabels:
        platform.gitops.io/role: {{ $name }}-pod-identity
    region: {{ $.Values.aws.region }}
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
