{{- range $name, $identity := .Values.identities }}
{{- if and $identity.policy (not (eq (toString $identity.enabled) "false")) }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ $name }}-pod-identity-policy
  annotations:
    crossplane.io/external-name: {{ $.Values.aws.clusterName }}-{{ $identity.policy.name }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "-3"
spec:
  forProvider:
    policy: |
{{ $identity.policy.document | indent 6 }}
    {{- if $identity.tags }}
    tags:
      {{- toYaml $identity.tags | nindent 6 }}
    {{- end }}
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
