{{- range $name, $identity := .Values.identities }}
{{- if not (eq (toString $identity.enabled) "false") }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: {{ $name }}-pod-identity-role
  annotations:
    crossplane.io/external-name: {{ $identity.roleName }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    platform.gitops.io/role: {{ $name }}-pod-identity
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "pods.eks.amazonaws.com"
            },
            "Action": [
              "sts:AssumeRole",
              "sts:TagSession"
            ]
          }
        ]
      }
    {{- if $identity.tags }}
    tags:
      {{- toYaml $identity.tags | nindent 6 }}
    {{- end }}
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
