apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-config
      containers:
        - name: keycloak
          env:
            - name: KEYCLOAK_ADMIN
              value: 'modernengg-admin'
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-config
                  key: POSTGRES_PASSWORD
            # Add environment variables for proxy and security
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: keycloak-config
          args:
            - start
          readinessProbe:
            httpGet:
              path: /keycloak/realms/master
              port: 8080  
          livenessProbe:
            httpGet:
              path: /keycloak/realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: keycloak-config
              mountPath: "/opt/keycloak/conf"
              readOnly: true
