apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-bucket-template-ack
  title: S3 Bucket Template ACK
  description: Create S3 bucket using OAM and ACK
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Provide S3 Bucket Information
      required:
        - bucket_name
        - environment
        - region
      properties:
        bucket_name:
          title: Bucket Name
          type: string
          description: Name of the S3 bucket
        environment:
          title: Environment
          type: string
          description: The environment (e.g., dev, prod)
          enum: ['dev', 'prod']
        region:
          title: Region
          type: string
          description: AWS region for the S3 bucket
          default: us-west-2
        namespace:
          default: default
          title: Existing namespace to create this resource
          type: string
        configuration:
          default: standard
          title: Configuration of your S3 Bucket
          type: string
          enum: ['standard', 'intelligent-tiering']
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          bucket_name: ${{ parameters.bucket_name }}
          configuration: ${{ parameters.configuration }}
          namespace: ${{ parameters.namespace }}
          environment: ${{ parameters.environment }}
          region: ${{ parameters.region }}
          repoUrl: ${{ steps['fetchSystem'].output.entity.spec.hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab
      input:
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.hostname }}?repo=${{parameters.bucket_name}}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        defaultBranch: main
        gitTimeout: 120
    - id: register
      name: Register in catalog
      action: catalog:register
      input:
        repoContentsUrl: https://${{ steps['fetchSystem'].output.entity.spec.hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.bucket_name}}/-/blob/main
        catalogInfoPath: "/catalog-info.yaml"
    - id: create-argocd-repo-secret
      name: Create ArgoCD Repository Secret
      action: kube:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: argocd-repo-${{parameters.bucket_name}}
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repository
          stringData:
            type: git
            url: https://${{ steps['fetchSystem'].output.entity.spec.hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.bucket_name}}.git
            username: ${{ steps['fetchSystem'].output.entity.spec.gituser }}
            password: glpat-SIQhHhoNuFQk3lTni8VndW86MQp1OjIH.01.0w1y33w8j
    - id: create-argocd-app
      name: Create ArgoCD App
      action: argocd:create-resources
      input:
        appName: ${{parameters.bucket_name}}
        namespace: default
        argoInstance: in-cluster
        projectName: ${{parameters.bucket_name}}-project
        repoUrl: https://${{ steps['fetchSystem'].output.entity.spec.hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.bucket_name}}.git
        path: "manifests"
    - id: register
      name: Register in catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
    - id: template-output
      name: Template Output
      action: debug:log
      input:
        listWorkspace: true
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: View catalog-info.yaml
        url: ${{ steps.publish.output.remoteUrl }}/-/blob/main/catalog-info.yaml
    text:
      - title: Manual Catalog Registration
        content: |
          To register this component in Backstage catalog, go to:
          /catalog-import
          
          And add this URL:
          ${{ steps.publish.output.remoteUrl }}/-/blob/main/catalog-info.yaml
