# EKS Pod Identity Association for External Secrets Operator
# Created by Crossplane on Kind during bootstrap, then adopted by
# Crossplane on the hub via crossplane.io/external-name annotation
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: eso-pod-identity
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: a-yctoakuwrwza5tbao
spec:
  forProvider:
    clusterName: hub
    namespace: external-secrets
    serviceAccount: external-secrets-sa
    roleArnRef:
      name: eso-pod-identity-role
    region: us-west-2
  providerConfigRef:
    name: default
