apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rust-application
spec:
  components:
    - name: rust-webservice
      type: appmod-service
      properties:
        image: <image>
        image_name: rust-app
        port: 8080
        targetPort: 8080
        replicas: 2
        appPath: "/rust-app"
        serviceAccount: rust-service-account-sa
        env:
          - name: APP_ENV
            value: "DEV"
          - name: TABLE_NAME
            value: rust-app-table
        readinessProbe:
          httpGet:
            path: /rust-app/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            memory: "512Mi"
      traits:
        - type: path-based-ingress
          properties:
            domain: "*.elb.us-west-2.amazonaws.com"
            rewritePath: true
            http:
              /rust-app: 8080

    - name: rust-service-account-sa
      type: dp-service-account
      properties:
        componentNamesForAccess:
          - rust-dynamodb
        clusterName: peeks-spoke-dev
        clusterRegion: us-west-2

    - name: rust-dynamodb
      type: dynamodb-table
      properties:
        tableName: rust-app-table
        partitionKeyName: partition_key
        sortKeyName: sort_key
        region: us-west-2
      traits:
        - type: component-iam-policy
          properties:
            service: dynamodb
