apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: eks-cluster-template
  title: Setup EKS Environment
  description: |
    Creates a new Amazon EKS AutoMode cluster using Kro and ACK controllers.
    
    This template uses:
    - **Kro (Kubernetes Resource Orchestrator)**: Declarative resource graph for cluster creation
    - **ACK (AWS Controllers for Kubernetes)**: Manages AWS resources (VPC, EKS, IAM) from Kubernetes
    - **GitOps**: Automatically registers the new cluster with ArgoCD hub for continuous deployment
    
    The cluster will be fully configured with networking, IAM roles, and ready for workload deployment.
spec:
  owner: user:guest
  type: service
  parameters:
    - title: EKS Cluster Information
      required:
        - clusterName
        - environment
        - region
        - k8sVersion
        - tenant
      properties:
        clusterName:
          title: EKS Cluster Name
          type: string
          description: Name of the EKS cluster
          ui:autofocus: true
          default: "peeks-spoke-staging"
        environment:
          title: Environment
          type: string
          description: Environment (e.g., dev, test, prod)
          default: "dev"
        region:
          title: AWS Region
          type: string
          description: AWS Region for the EKS cluster
          default: "us-west-2"
        k8sVersion:
          title: Kubernetes Version
          type: string
          description: Kubernetes version for the EKS cluster
          default: "1.35"
        accountId:
          title: Account ID
          type: string
          description: AWS Account ID (optional - defaults to system default)
          ui:help: "Enter your AWS Account ID (12 digits) or leave empty for default"
        managementAccountId:
          title: Management Account ID
          type: string
          description: AWS Management Account ID
          ui:help: "Enter your AWS Management Account ID (12 digits)"
        tenant:
          title: Tenant Name
          type: string
          description: Name of the tenant
          default: "control-plane"
        resourcePrefix:
          title: Resource Prefix
          type: string
          description: Prefix for AWS resources
          default: "peeks"
        repoHostUrl:
          type: string
          ui:widget: hidden
        repoUsername:
          type: string
          ui:widget: hidden
        repoName:
          type: string
          default: platform-on-eks-workshop
          ui:widget: hidden
        ingressDomainName:
          type: string
          default: <ingress_domain_name>
          ui:widget: hidden
    - title: Git Repository URLs
      properties:
        addonsRepoUrl:
          title: Addons Repository URL
          type: string
          description: Git repository URL for addons
          ui:help: "Leave empty to use default system repository"
        fleetRepoUrl:
          title: Fleet Repository URL
          type: string
          description: Git repository URL for fleet
          ui:help: "Leave empty to use default system repository"
        platformRepoUrl:
          title: Platform Repository URL
          type: string
          description: Git repository URL for platform
          ui:help: "Leave empty to use default system repository"
        workloadRepoUrl:
          title: Workload Repository URL
          type: string
          description: Git repository URL for workload
          ui:help: "Will be auto-populated from system configuration"
    - title: Cluster Addons Configuration
      properties:
        enableIngressClassAlb:
          title: Enable Ingress Class ALB
          type: boolean
          description: Enable Ingress Class ALB addon
          default: false
        enableArgoRollouts:
          title: Enable Argo Rollouts
          type: boolean
          description: Enable Argo Rollouts addon
          default: true
        enableMetricsServer:
          title: Enable Metrics Server
          type: boolean
          description: Enable Metrics Server addon
          default: true
        enableExternalSecrets:
          title: Enable External Secrets
          type: boolean
          description: Enable External Secrets addon
          default: true
        enableKyverno:
          title: Enable Kyverno
          type: boolean
          description: Enable Kyverno addon
          default: true
        enableKyvernoPolicies:
          title: Enable Kyverno Policies
          type: boolean
          description: Enable Kyverno Policies addon
          default: false
        enableKyvernoPolicyReporter:
          title: Enable Kyverno Policy Reporter
          type: boolean
          description: Enable Kyverno Policy Reporter addon
          default: false
        enableCrossplane:
          title: Enable Crossplane
          type: boolean
          description: Enable Crossplane addon
          default: true
        enableCrossplaneAws:
          title: Enable Crossplane AWS
          type: boolean
          description: Enable Crossplane AWS addon
          default: true
        enableFlux:
          title: Enable Flux
          type: boolean
          description: Enable Flux addon
          default: true
        enableIngressNginx:
          title: Enable Ingress Nginx
          type: boolean
          description: Enable Ingress Nginx addon
          default: true
        enablePlatformManifests:
          title: Enable Platform Manifests
          type: boolean
          description: Enable Platform Manifests addon
          default: true
        enableKubevela:
          title: Enable KubeVela
          type: boolean
          description: Enable KubeVela addon
          default: true
        enableCertManager:
          title: Enable Cert Manager
          type: boolean
          description: Enable Cert Manager addon
          default: true
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - id: checkout
      name: Checkout repository
      action: fetch:plain
      input:
        url: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{ parameters.repoName }}
        targetPath: ./repo
    - id: addCluster
      name: Add new Clusters
      # if: ${{ (parameters.accountId or steps['fetchSystem'].output.entity.spec.aws_account_id) !== (parameters.managementAccountId or steps['fetchSystem'].output.entity.spec.aws_account_id) }}
      action: roadiehq:utils:fs:append
      input:
        path: ./repo/gitops/addons/tenants/${{ parameters.tenant }}/default/addons/multi-acct/values.yaml
        content: "\n  ${{ parameters.clusterName }}: \"${{ parameters.accountId or steps['fetchSystem'].output.entity.spec.aws_account_id }}\""
    - id: addKroClusterConfig
      name: Update kro Clusters Configuration
      action: roadiehq:utils:fs:append
      input:
        path: ./repo/gitops/fleet/kro-values/tenants/${{ parameters.tenant }}/kro-clusters/values.yaml
        content: "\n  ${{ parameters.clusterName }}:\n    managementAccountId: \"${{ parameters.managementAccountId or steps['fetchSystem'].output.entity.spec.aws_account_id }}\"\n    accountId: \"${{ parameters.accountId or steps['fetchSystem'].output.entity.spec.aws_account_id }}\"\n    tenant: \"${{ parameters.tenant }}\"\n    environment: \"${{ parameters.environment }}\"\n    region: \"${{ parameters.region }}\"\n    k8sVersion: \"${{ parameters.k8sVersion }}\"\n    resourcePrefix: \"${{ parameters.resourcePrefix }}\"\n    adminRoleName: \"${{ steps['fetchSystem'].output.entity.spec.admin_role_name }}\"\n    gitops:\n      addonsRepoUrl: \"${{ parameters.addonsRepoUrl or 'https://' + steps['fetchSystem'].output.entity.spec.gitlab_hostname + '/' + steps['fetchSystem'].output.entity.spec.gituser + '/platform-on-eks-workshop.git' }}\"\n      fleetRepoUrl: \"${{ parameters.fleetRepoUrl or 'https://' + steps['fetchSystem'].output.entity.spec.gitlab_hostname + '/' + steps['fetchSystem'].output.entity.spec.gituser + '/platform-on-eks-workshop.git' }}\"\n      platformRepoUrl: \"${{ parameters.platformRepoUrl or 'https://' + steps['fetchSystem'].output.entity.spec.gitlab_hostname + '/' + steps['fetchSystem'].output.entity.spec.gituser + '/platform-on-eks-workshop.git' }}\"\n      workloadRepoUrl: \"${{ parameters.workloadRepoUrl or 'https://' + steps['fetchSystem'].output.entity.spec.gitlab_hostname + '/' + steps['fetchSystem'].output.entity.spec.gituser + '/platform-on-eks-workshop.git' }}\"\n    addons:\n      enable_ingress_class_alb: \"${{ parameters.enableIngressClassAlb }}\"\n      enable_argo_rollouts: \"${{ parameters.enableArgoRollouts }}\"\n      enable_metrics_server: \"${{ parameters.enableMetricsServer }}\"\n      enable_external_secrets: \"${{ parameters.enableExternalSecrets }}\"\n      enable_kyverno: \"${{ parameters.enableKyverno }}\"\n      enable_kyverno_policies: \"${{ parameters.enableKyvernoPolicies }}\"\n      enable_kyverno_policy_reporter: \"${{ parameters.enableKyvernoPolicyReporter }}\"\n      enable_aws_efs_csi_driver: \"${{ parameters.enableAwsEfsCsiDriver }}\"\n      enable_flux: \"true\"\n      enable_cert_manager: \"true\"\n      enable_crossplane: \"true\"\n      enable_crossplane_aws: \"true\"\n      enable_ingress_nginx: \"true\"\n      enable_kubevela: \"true\"\n      enable_platform_manifests: \"true\"\n      enable_ack_iam: \"false\"\n      enable_ack_eks: \"false\"\n      enable_ack_ec2: \"false\"\n      enable_ack_ecr: \"false\"\n      enable_ack_s3: \"false\"\n      enable_ack_dynamodb: \"false\"\n      enable_ack_efs: \"false\"\n      enable_kro: \"false\""
    - id: addComponent
      name: Add new component for Cluster
      action: roadiehq:utils:fs:write
      input:
        path: ./repo/platform/backstage/components/${{ parameters.clusterName }}.yaml
        content: |
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.clusterName }}
            description: EKS Cluster deployed by kro
            links:
              - url: https://${{ steps['fetchSystem'].output.entity.spec.argocd_hostname }}/applications/argocd/clusters
                title: ArgoCD App URL
                icon: externalLink
              - url: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{ parameters.repoName }}/-/blob/main/fleet/kro-values/tenants/tenant1/kro-clusters/values.yaml
                title: Git Repo URL
                icon: github
          spec:
            owner: guests
            lifecycle: experimental
            type: service
    # - id: mergeConfig
    #   name: Update Clusters Configuration
    #   action: roadiehq:utils:merge
    #   input:
    #     path: ./repo/gitops/fleet/kro-values/tenants/tenant1/kro-clusters/values.yaml
    #     content:
    #       clusters:
    #         '${{ parameters.clusterName }}': '${{ parameters.accountId }}'
    #         preserveYamlComments: true
    # - id: parse
    #   name: read file
    #   action: roadiehq:utils:fs:parse
    #   input:
    #     path: ./repo/gitops/addons/tenants/tenant1/default/addons/multi-acct/values.yaml
    # - id: log
    #   name: Console.log
    #   action: debug:log
    #   input:
    #     message: |
    #       Content: `${{ steps['parse'].output.content }}`
    - id: createGitlabMergeRequest
      name: Create a Merge Request
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}?repo=${{ parameters.repoName }}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        title: Add new EKS cluster ${{ parameters.clusterName }}
        description: |
          Add new EKS cluster ${{ parameters.clusterName }} to the platform
          
          Changes:
          - Added cluster configuration to multi-acct values
          - Added kro cluster configuration  
          - Added Backstage component definition
        sourcePath: ./repo
        targetPath: .
        branchName: cluster-${{ parameters.clusterName }}-${{ parameters.environment }}
        removeSourceBranch: true
        commitAction: auto
    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoUrl: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{ parameters.repoName }}/-/blob/main/platform/backstage/components/${{ parameters.clusterName }}.yaml
        optional: true
  output:
    links:
      - title: Gitlab MergeRequest URL
        url: ${{ steps.createGitlabMergeRequest.output.mergeRequestUrl }}
