apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates an RDS Aurora Postgres DB
  name: create-env-aurora-postgres
  title: Create RDS Aurora Postgres Database
spec:
  owner: guest
  type: service
  parameters:
    - properties:
        name:
          title: Unique Name of the Database
          type: string
        namespace:
          default: flux-system
          title: Enter namespace within the EKS cluster to deploy this
          type: string
        aws_region:
          default: us-west-2
          title: Region
          type: string
      title: Configuration Options
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - action: fetch:template
      id: fetch-base
      input:
        url: ./templates-env-aurora-postgres/
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          aws_region: ${{ parameters.aws_region }}
          repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}
      name: Fetch Base
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab
      input:
        # Hard coded value for this demo purposes only.
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}?repo=${{parameters.name}}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        defaultBranch: main
    - id: create-argocd-app
      name: Create ArgoCD App
      action: argocd:create-app
      input:
        appName: ${{parameters.name}}
        appNamespace: ${{parameters.namespace}}
        argoInstance: in-cluster
        projectName: default
        # necessary until we generate our own cert
        repoUrl: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.name}}
        path: "manifests"
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}

