apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-deploy-without-git-repo
  title: App Deployment without Git Repo
  description: Creates a ArgocCD for deploying an App for an existing Git Repo
  tags:
    - app-deploy
    - gitlab
    - argocd
spec:
  owner: guest
  type: service
  parameters:
    - title: Provide App Information
      required:
        - appName
        - repoPath
        - repoName
        - environment
      properties:
        appName:
          title: App Name
          type: string
          description: Name of the App
        environment:
          title: Environment
          type: string
          description: The environment (e.g., dev, prod)
          enum: ['dev-cluster', 'prod-cluster', 'in-cluster']
        repoName:
          title: Repo Name of your GitLab Repo integrated with Backstage
          type: string
          pattern: ^[a-zA-Z0-9-_.]+$
        repoPath:
          title: Path of Git Repo to sync for GitOps
          type: string
        appNamespace:
          title: App Namespace
          type: string
          description: The namespace where the app should be deployed
          default: default
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - id: create-argocd-project
      name: Create ArgoCD Project
      action: kube:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: AppProject
          metadata:
            name: ${{parameters.appName}}-project
            namespace: argocd
          spec:
            description: Project for ${{parameters.appName}} application
            sourceNamespaces:
            - argocd
            sourceRepos:
            - https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.repoName}}.git
            destinations:
            - namespace: ${{parameters.appNamespace}}
              name: ${{ steps['fetchSystem'].output.entity.spec.hub_cluster_name }}
            clusterResourceWhitelist:
            - group: '*'
              kind: '*'
            namespaceResourceWhitelist:
            - group: '*'
              kind: '*'
    - id: create-argocd-app
      name: Create ArgoCD App
      action: kube:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{parameters.appName}}
            namespace: argocd
            labels:
              backstage-name: ${{parameters.appName}}
            finalizers:
            - resources-finalizer.argocd.argoproj.io
          spec:
            project: ${{parameters.appName}}-project
            destination:
              namespace: ${{parameters.appNamespace}}
              name: ${{ steps['fetchSystem'].output.entity.spec.hub_cluster_name }}
            source:
              repoURL: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.repoName}}.git
              targetRevision: HEAD
              path: ${{parameters.repoPath}}
            syncPolicy:
              automated:
                allowEmpty: true
                prune: false
                selfHeal: true
              retry:
                backoff:
                  duration: 5s
                  factor: 2
                  maxDuration: 5m
                limit: 10
              syncOptions:
              - CreateNamespace=false
              - FailOnSharedResource=true
    - id: template-output
      name: Template Output
      action: debug:log
      input:
        listWorkspace: true
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
