apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Deploy dev and prod EKS clusters with GitOps configuration.
  name: create-dev-and-prod-env
  title: Create Dev and Prod Environment
spec:
  owner: guest
  type: service
  parameters:
    - title: Configuration Options
      required:
        - name
      properties:
        name:
          title: Name of the component
          type: string
          description: Name for the dev and prod environment
          ui:autofocus: true
        namespace:
          default: flux-system
          title: Enter namespace within the EKS cluster to deploy this
          type: string
        aws_region:
          default: "${{ steps['fetchSystem'].output.entity.spec.aws_region }}"
          title: Region
          type: string
        repoHostUrl:
          type: string
          default: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}
          ui:widget: hidden
        repoUsername:
          type: string
          default: "${{ steps['fetchSystem'].output.entity.spec.gituser }}"
          ui:widget: hidden
        repoName:
          type: string
          default: platform-on-eks-workshop
          ui:widget: hidden
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - action: fetch:template
      id: fetch-base
      input:
        url: ./templates-create-dev-and-prod-env/
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          aws_region: ${{ parameters.aws_region }}
          repoUrl: https://${{ parameters.repoHostUrl }}/${{ parameters.repoUsername }}
      name: Fetch Base
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ parameters.repoHostUrl }}?repo=${{parameters.name}}&owner=${{ parameters.repoUsername }}
        title: Add new dev and prod environment - ${{parameters.name}}
        description: Create dev and prod clusters template
        sourcePath: .
        targetPath: .
        branchName: add-${{parameters.name}}-env
        removeSourceBranch: true
        commitAction: auto
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: View Merge Request
        icon: gitlab
        url: ${{ steps['publish'].output.mergeRequestUrl }}
