apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: |
    Deploys dev and prod clusters on EKS.

    ⚠️  PREREQUISITE: Create GitLab repository first!

    **Option 1: Use the script (recommended)**
    ```bash
    cd /home/ec2-user/environment/platform-on-eks-workshop
    ./scripts/create-gitlab-repo.sh ${{ parameters.name }}
    ```

    **Option 2: Manual command**
    ```bash
    curl -X POST "$GITLABURL/api/v4/projects" \
      -H "PRIVATE-TOKEN: $GITLABPW" \
      -H "Content-Type: application/json" \
      -d '{"name":"${{ parameters.name }}","path":"${{ parameters.name }}","description":"Dev and Prod environment","visibility":"private","initialize_with_readme":true}'
    ```

    Then continue with this template.
  name: create-dev-and-prod-env
  title: Create Dev and Prod Environment
spec:
  owner: guest
  type: service
  parameters:
    - title: Configuration Options
      required:
        - name
      properties:
        name:
          title: Name of the component
          type: string
          description: Name for the dev and prod environment
          ui:autofocus: true
        namespace:
          default: flux-system
          title: Enter namespace within the EKS cluster to deploy this
          type: string
        aws_region:
          default: us-east-1
          title: Region
          type: string
        repoHostUrl:
          type: string
          default: d1d6f396lhftfb.cloudfront.net
          ui:widget: hidden
        repoUsername:
          type: string
          default: user1
          ui:widget: hidden
        repoName:
          type: string
          default: platform-on-eks-workshop
          ui:widget: hidden
  steps:
    - action: fetch:template
      id: fetch-base
      input:
        url: ./templates-create-dev-and-prod-env/
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          aws_region: ${{ parameters.aws_region }}
          repoUrl: https://${{ parameters.repoHostUrl }}/${{ parameters.repoUsername }}
      name: Fetch Base
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ parameters.repoHostUrl }}?repo=${{parameters.name}}&owner=${{ parameters.repoUsername }}
        title: Add new dev and prod environment - ${{parameters.name}}
        description: Create dev and prod clusters template
        sourcePath: .
        targetPath: .
        branchName: add-${{parameters.name}}-env
        removeSourceBranch: true
        commitAction: auto
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'catalog-info.yaml'
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: View Merge Request
        icon: gitlab
        url: ${{ steps['publish'].output.mergeRequestUrl }}
