#!/usr/bin/env bash
#
# sync-apex-skills.sh — Vendor a pinned subset of APEX EKS skills into PEEKS.
#
# WHAT: Clones the APEX skills repo (aws-samples/sample-apex-skills) at a PINNED
#       tag and copies a fixed set of EKS skills into hack/.kiro/skills/ so they
#       ship by default in every participant's Kiro `peeks` agent — no manual
#       step, no network dependency at workshop boot.
#
# WHO:  Maintainer script. Run it manually (in a dev/CI checkout), review the
#       resulting diff, and commit. It is NOT run on participant IDEs.
#
# REFRESH: bump APEX_REF below to a newer stable tag, re-run, review, commit.
#
# GUARANTEES:
#   - Pinned tag + recorded commit SHA (never a floating branch like `main`).
#   - Idempotent: re-running with the same APEX_REF produces identical output.
#   - Never touches the PEEKS-owned skills (troubleshoot-kro, troubleshoot-platform,
#     manage-addons); aborts on any name collision.
#   - Fails cleanly with a clear message if the network or tag is unavailable.
#   - No hardcoded account IDs, regions, or other environment-specific values.

set -euo pipefail

# ---------------------------------------------------------------------------
# Pinned APEX release — DO NOT use a floating branch (security/reproducibility).
# ---------------------------------------------------------------------------
APEX_REPO="https://github.com/aws-samples/sample-apex-skills"
APEX_REF="v1.2.0"   # pinned tag; bump to refresh

# EKS skills to vendor (subset of the APEX skills/ directory).
APEX_SKILLS=(
  eks-recon
  eks-platform-engineering
  eks-best-practices
  eks-security
  eks-upgrade-check
  eks-cost-intelligence
)

# PEEKS-owned skills that must never be overwritten by this script.
PEEKS_SKILLS=(
  troubleshoot-kro
  troubleshoot-platform
  manage-addons
)

# ---------------------------------------------------------------------------
# Resolve paths relative to the repo (this script lives in scripts/).
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/hack/.kiro/skills"

log() { printf '\033[0;36m▸ %s\033[0m\n' "$*"; }
ok()  { printf '\033[0;32m✓ %s\033[0m\n' "$*"; }
err() { printf '\033[0;31m✗ %s\033[0m\n' "$*" >&2; }

# ---------------------------------------------------------------------------
# Preconditions.
# ---------------------------------------------------------------------------
command -v git >/dev/null 2>&1 || { err "git is required but not found in PATH"; exit 1; }
[ -d "$SKILLS_DIR" ] || { err "skills dir not found: $SKILLS_DIR — run this from the PEEKS repo"; exit 1; }

# Collision guard: an APEX skill must never share a name with a PEEKS skill.
for a in "${APEX_SKILLS[@]}"; do
  for p in "${PEEKS_SKILLS[@]}"; do
    if [ "$a" = "$p" ]; then
      err "name collision: APEX skill '$a' would overwrite PEEKS skill '$p' — aborting"
      exit 1
    fi
  done
done

# ---------------------------------------------------------------------------
# Clone the pinned tag into a temp dir (cleaned up on exit).
# ---------------------------------------------------------------------------
TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

log "Cloning ${APEX_REPO} @ ${APEX_REF} ..."
if ! git clone --quiet --depth 1 --branch "$APEX_REF" "$APEX_REPO" "$TMP/apex" 2>/dev/null; then
  err "failed to clone ${APEX_REPO} at tag ${APEX_REF} (no network, or tag does not exist)"
  exit 1
fi

APEX_SHA="$(git -C "$TMP/apex" rev-parse HEAD)"
ok "Cloned ${APEX_REF} (${APEX_SHA})"

SRC="$TMP/apex/skills"
[ -d "$SRC" ] || { err "expected 'skills/' directory not found in APEX repo at ${APEX_REF}"; exit 1; }

# Pre-flight: verify every requested skill exists (with a SKILL.md) BEFORE we
# modify anything, so a partial/renamed upstream never leaves a half-applied state.
for s in "${APEX_SKILLS[@]}"; do
  if [ ! -f "$SRC/$s/SKILL.md" ]; then
    err "skill '$s' (or its SKILL.md) not found in APEX ${APEX_REF} — aborting, nothing changed"
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# Vendor the skills. Idempotent: drop any prior vendored copy, then copy fresh.
# PEEKS skills are never in APEX_SKILLS, so they are untouched.
# ---------------------------------------------------------------------------
for s in "${APEX_SKILLS[@]}"; do
  rm -rf "${SKILLS_DIR:?}/$s"
  cp -R "$SRC/$s" "$SKILLS_DIR/$s"
  ok "vendored $s"
done

# ---------------------------------------------------------------------------
# Record pinned provenance (tag + commit SHA) for auditability.
# ---------------------------------------------------------------------------
cat > "$SKILLS_DIR/APEX_VERSION" <<EOF
# APEX skills vendored into PEEKS — generated by scripts/sync-apex-skills.sh.
# DO NOT EDIT BY HAND. Refresh by bumping APEX_REF in the script and re-running.
repo=${APEX_REPO}
tag=${APEX_REF}
commit=${APEX_SHA}
skills=${APEX_SKILLS[*]}
EOF
ok "wrote $SKILLS_DIR/APEX_VERSION"

log "Done — vendored ${#APEX_SKILLS[@]} APEX skills at ${APEX_REF} into hack/.kiro/skills/"
