apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: pdf-agent-app
  namespace: default
spec:
  components:
    - name: pdf-processor
      type: kagent-with-rollout
      properties:
        name: pdf-processor
        namespace: kagent
        image: ghcr.io/my-org/pdf-agent:v1.0.0
        replicas: 3
        description: "PDF processing agent with document generation capabilities"
        
        # Model configuration
        modelConfig:
          model: anthropic.claude-sonnet-4-20250514-v1:0
          apiKeySecret:
            name: bedrock-secret
            key: aws-access-key-id
        
        # System message / prompt
        systemMessage: |
          You are a helpful PDF processing agent.
          You can extract text from PDFs and generate new PDF documents.
          Always be concise and provide actionable solutions.
        
        # Service account for AWS IRSA
        serviceAccount: bedrock-agent-sa
        
        # MCP servers
        mcpServers:
          - name: pdf-tools
            port: 3000
          - name: k8s-tools
            port: 3001
        
        # Tools to enable
        tools:
          - name: generate_pdf
            mcpServer: pdf-tools
          - name: extract_text
            mcpServer: pdf-tools
          - name: k8s_get_pods
            mcpServer: k8s-tools
          - name: k8s_get_logs
            mcpServer: k8s-tools
        
        # Argo Rollouts canary strategy
        rolloutStrategy:
          canary:
            steps:
              - setWeight: 20
              - pause:
                  duration: 5m
              - setWeight: 50
              - pause:
                  duration: 5m
              - setWeight: 80
              - pause:
                  duration: 2m
