apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: kagent-with-rollout
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "Kagent-compatible agent with Argo Rollouts support"
spec:
  workload:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
  schematic:
    cue:
      template: |
        import "strings"
        
        output: {
          apiVersion: "argoproj.io/v1alpha1"
          kind: "Rollout"
          metadata: {
            name: parameter.name
            namespace: parameter.namespace
            labels: {
              "kagent.dev/agent": parameter.name
              "app.kubernetes.io/name": parameter.name
              "app.kubernetes.io/component": "ai-agent"
            }
          }
          spec: {
            replicas: parameter.replicas
            strategy: {
              if parameter.rolloutStrategy.canary != _|_ {
                canary: {
                  canaryService: parameter.name + "-canary"
                  stableService: parameter.name + "-stable"
                  steps: parameter.rolloutStrategy.canary.steps
                  if parameter.rolloutStrategy.canary.trafficRouting != _|_ {
                    trafficRouting: parameter.rolloutStrategy.canary.trafficRouting
                  }
                  if parameter.rolloutStrategy.canary.dynamicStableScale != _|_ {
                    dynamicStableScale: parameter.rolloutStrategy.canary.dynamicStableScale
                  }
                }
              }
              if parameter.rolloutStrategy.blueGreen != _|_ {
                blueGreen: {
                  activeService: parameter.name + "-stable"
                  previewService: parameter.name + "-preview"
                  autoPromotionEnabled: parameter.rolloutStrategy.blueGreen.autoPromotionEnabled
                  if parameter.rolloutStrategy.blueGreen.scaleDownDelaySeconds != _|_ {
                    scaleDownDelaySeconds: parameter.rolloutStrategy.blueGreen.scaleDownDelaySeconds
                  }
                }
              }
            }
            selector: {
              matchLabels: {
                "kagent.dev/agent": parameter.name
              }
            }
            template: {
              metadata: {
                labels: {
                  "kagent.dev/agent": parameter.name
                  "app.kubernetes.io/name": parameter.name
                }
              }
              spec: {
                serviceAccountName: parameter.serviceAccount
                containers: [{
                  name: "agent"
                  image: parameter.image
                  ports: [{
                    name: "a2a"
                    containerPort: 8083
                    protocol: "TCP"
                  }]
                  env: [
                    {
                      name: "MODEL_ID"
                      value: parameter.modelConfig.model
                    },
                    {
                      name: "SYSTEM_PROMPT"
                      value: parameter.systemMessage
                    },
                  ] + [
                    if parameter.modelConfig.agentGatewayUrl != _|_ {
                      {
                        name: "AGENTGATEWAY_URL"
                        value: parameter.modelConfig.agentGatewayUrl
                      }
                    },
                  ] + [
                    if parameter.modelConfig.apiKeySecret != _|_ {
                      {
                        name: "MODEL_API_KEY"
                        valueFrom: {
                          secretKeyRef: {
                            name: parameter.modelConfig.apiKeySecret.name
                            key: parameter.modelConfig.apiKeySecret.key
                          }
                        }
                      }
                    },
                  ] + [
                    if parameter.memoryConfig != _|_ {
                      {
                        name: "MEMORY_TYPE"
                        value: parameter.memoryConfig.type
                      }
                    },
                  ] + [
                    if parameter.memoryConfig != _|_ {
                      {
                        name: "MEMORY_COMPONENT"
                        value: parameter.memoryConfig.component
                      }
                    },
                  ] + [
                    if parameter.agentcoreConfig != _|_ && parameter.agentcoreConfig.browser != _|_ {
                      {
                        name: "AGENTCORE_BROWSER_COMPONENT"
                        value: parameter.agentcoreConfig.browser.component
                      }
                    },
                  ] + [
                    if parameter.agentcoreConfig != _|_ && parameter.agentcoreConfig.browser != _|_ && parameter.agentcoreConfig.browser.enabled != _|_ {
                      {
                        name: "AGENTCORE_BROWSER_ENABLED"
                        value: "\(parameter.agentcoreConfig.browser.enabled)"
                      }
                    },
                  ] + [
                    if parameter.agentcoreConfig != _|_ && parameter.agentcoreConfig.codeInterpreter != _|_ {
                      {
                        name: "AGENTCORE_CODE_INTERPRETER_COMPONENT"
                        value: parameter.agentcoreConfig.codeInterpreter.component
                      }
                    },
                  ] + [
                    if parameter.agentcoreConfig != _|_ && parameter.agentcoreConfig.codeInterpreter != _|_ && parameter.agentcoreConfig.codeInterpreter.enabled != _|_ {
                      {
                        name: "AGENTCORE_CODE_INTERPRETER_ENABLED"
                        value: "\(parameter.agentcoreConfig.codeInterpreter.enabled)"
                      }
                    },
                  ] + [
                    if parameter.mcpServers != _|_ && len(parameter.mcpServers) > 0 {
                      {
                        name: "MCP_SERVERS"
                        value: strings.Join([for s in parameter.mcpServers {
                          "\(s.name)=http://\(s.name).\(parameter.namespace).svc.cluster.local:\(s.port)"
                        }], ",")
                      }
                    },
                  ] + [
                    if parameter.tools != _|_ && len(parameter.tools) > 0 {
                      {
                        name: "ENABLED_TOOLS"
                        value: strings.Join([for t in parameter.tools {t.name}], ",")
                      }
                    },
                  ]
                  livenessProbe: {
                    httpGet: {
                      path: "/.well-known/agent.json"
                      port: 8083
                    }
                    initialDelaySeconds: 10
                    periodSeconds: 30
                  }
                  readinessProbe: {
                    httpGet: {
                      path: "/.well-known/agent.json"
                      port: 8083
                    }
                    initialDelaySeconds: 5
                    periodSeconds: 10
                  }
                }]
              }
            }
          }
        }
        
        outputs: {
          // Stable service (always created)
          stableService: {
            apiVersion: "v1"
            kind: "Service"
            metadata: {
              name: parameter.name + "-stable"
              namespace: parameter.namespace
              labels: {
                "kagent.dev/agent": parameter.name
                "app.kubernetes.io/name": parameter.name
              }
            }
            spec: {
              selector: {
                "kagent.dev/agent": parameter.name
              }
              ports: [{
                name: "a2a"
                port: 8083
                targetPort: 8083
                protocol: "TCP"
              }]
              type: "ClusterIP"
            }
          }
          
          // Canary service (for canary deployments)
          if parameter.rolloutStrategy.canary != _|_ {
            canaryService: {
              apiVersion: "v1"
              kind: "Service"
              metadata: {
                name: parameter.name + "-canary"
                namespace: parameter.namespace
                labels: {
                  "kagent.dev/agent": parameter.name
                  "app.kubernetes.io/name": parameter.name
                }
              }
              spec: {
                selector: {
                  "kagent.dev/agent": parameter.name
                }
                ports: [{
                  name: "a2a"
                  port: 8083
                  targetPort: 8083
                  protocol: "TCP"
                }]
                type: "ClusterIP"
              }
            }
          }
          
          // Preview service (for blue-green deployments)
          if parameter.rolloutStrategy.blueGreen != _|_ {
            previewService: {
              apiVersion: "v1"
              kind: "Service"
              metadata: {
                name: parameter.name + "-preview"
                namespace: parameter.namespace
                labels: {
                  "kagent.dev/agent": parameter.name
                  "app.kubernetes.io/name": parameter.name
                }
              }
              spec: {
                selector: {
                  "kagent.dev/agent": parameter.name
                }
                ports: [{
                  name: "a2a"
                  port: 8083
                  targetPort: 8083
                  protocol: "TCP"
                }]
                type: "ClusterIP"
              }
            }
          }
          
          agentCard: {
            apiVersion: "v1"
            kind: "ConfigMap"
            metadata: {
              name: parameter.name + "-card"
              namespace: parameter.namespace
              labels: {
                "kagent.dev/agent": parameter.name
                "kagent.dev/type": "agent-card"
              }
            }
            data: {
              name: parameter.name
              description: parameter.description
              type: "BYO"
              if parameter.tools != _|_ && len(parameter.tools) > 0 {
                tools: strings.Join([for t in parameter.tools {t.name}], ",")
              }
            }
          }
        }
        
        parameter: {
          // Required fields
          name: string
          namespace: string
          image: string
          description: string
          systemMessage: string
          
          // Optional fields with defaults
          replicas: *3 | int
          serviceAccount: *"default" | string
          
          // Model configuration
          modelConfig: {
            model: string
            agentGatewayUrl?: string
            apiKeySecret?: {
              name: string
              key: string
            }
          }
          
          // Memory configuration
          memoryConfig?: {
            type: string
            component: string
          }
          
          // Agentcore configuration
          agentcoreConfig?: {
            browser?: {
              component: string
              enabled?: *true | bool
            }
            codeInterpreter?: {
              component: string
              enabled?: *true | bool
            }
          }
          
          // MCP servers - simplified
          mcpServers?: [...{
            name: string
            port: *3000 | int
          }]
          
          // Tools - Kagent-style references
          tools?: [...{
            name: string
            mcpServer?: string
          }]
          
          // Argo Rollouts strategy
          rolloutStrategy: {
            canary?: {
              steps: [...{
                setWeight?: int
                pause?: {
                  duration?: string | int
                }
              }]
              trafficRouting?: {
                alb?: {
                  ingress: string
                  rootService?: string
                  servicePort: int
                }
                istio?: {
                  virtualService: {
                    name: string
                    routes?: [...string]
                  }
                  destinationRule?: {
                    name: string
                    canarySubsetName?: string
                    stableSubsetName?: string
                  }
                }
              }
              dynamicStableScale?: bool
            }
            blueGreen?: {
              autoPromotionEnabled: *true | bool
              scaleDownDelaySeconds?: int
            }
          }
        }
