apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak.conf: |
    # Database
    # The database vendor.
    db=postgres

    # The username of the database user.
    db-username=keycloak
    db-url-host=postgresql.keycloak

    # Observability

    # If the server should expose healthcheck endpoints.
    #health-enabled=true

    # If the server should expose metrics endpoints.
    #metrics-enabled=true

    # The proxy address forwarding mode if the server is behind a reverse proxy.
    proxy=edge
    proxy-headers=xforwarded

    # Hostname configuration for CloudFront
    hostname-strict=false
    hostname-strict-backchannel=false
    hostname=d35j5kjjdl7nh.cloudfront.net
    hostname-url=https://d35j5kjjdl7nh.cloudfront.net/keycloak
    
    # HTTP configuration
    http-relative-path=keycloak
    http-enabled=true
    
    # Security and CORS configuration to fix 403 errors
    spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    spi-x509cert-lookup-provider=nginx
    
    # Enable CORS with wildcard for development (more permissive)
    spi-cors-provider=default
    spi-cors-default-allowed-origins=*
    spi-cors-default-allowed-methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
    spi-cors-default-allowed-headers=*
    spi-cors-default-exposed-headers=Location,Content-Type
    spi-cors-default-allow-credentials=true
    spi-cors-default-max-age=86400
    
    # Additional security headers (more permissive for iframe)
    spi-security-headers-provider=default
    spi-security-headers-default-content-security-policy=frame-ancestors *; frame-src *; object-src 'none';
    spi-security-headers-default-x-frame-options=ALLOWALL
    spi-security-headers-default-x-content-type-options=nosniff
    spi-security-headers-default-x-robots-tag=none
    spi-security-headers-default-x-xss-protection=1; mode=block
    
    # Additional settings for account console
    spi-account-provider=default
    spi-account-default-cors-allowed-origins=*
    spi-account-default-cors-allowed-methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
