apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak.conf: |
    # Database
    # The database vendor.
    db=postgres

    # The username of the database user.
    db-username=keycloak
    db-url-host=postgresql.keycloak

    # Observability

    # If the server should expose healthcheck endpoints.
    #health-enabled=true

    # If the server should expose metrics endpoints.
    #metrics-enabled=true

    # The proxy address forwarding mode if the server is behind a reverse proxy.
    proxy=edge
    proxy-headers=xforwarded

    # Hostname configuration for CloudFront
    hostname-strict=false
    hostname-strict-backchannel=false
    hostname=d35j5kjjdl7nh.cloudfront.net
    hostname-url=https://d35j5kjjdl7nh.cloudfront.net/keycloak
    
    # HTTP configuration
    http-relative-path=keycloak
    http-enabled=true
    
    # Security and CORS configuration to fix 403 errors
    spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    spi-x509cert-lookup-provider=nginx
    
    # Enable CORS for admin console and account console
    spi-cors-provider=default
    spi-cors-default-allowed-origins=https://d35j5kjjdl7nh.cloudfront.net
    spi-cors-default-allowed-methods=GET,POST,PUT,DELETE,OPTIONS
    spi-cors-default-allowed-headers=Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization
    spi-cors-default-exposed-headers=Location
    spi-cors-default-allow-credentials=true
    spi-cors-default-max-age=3600
    
    # Additional security headers to prevent iframe issues
    spi-security-headers-provider=default
    spi-security-headers-default-content-security-policy=frame-ancestors 'self' https://d35j5kjjdl7nh.cloudfront.net; frame-src 'self' https://d35j5kjjdl7nh.cloudfront.net; object-src 'none';
    spi-security-headers-default-x-frame-options=SAMEORIGIN
    spi-security-headers-default-x-content-type-options=nosniff
    spi-security-headers-default-x-robots-tag=none
    spi-security-headers-default-x-xss-protection=1; mode=block
    spi-security-headers-default-strict-transport-security=max-age=31536000; includeSubDomains
