apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-workflows
  namespace: argo
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/transforms.argo-server: >
      [{"type":"url-rewrite","urlRewriteConfig":{"rewrites":[{"regex":"^\\/argo-workflows\\/?(.*)$","replace":"/$1"}]}}]
spec:
  ingressClassName: "platform"
  rules:
    - host: {{ .Values.ingress_domain_name }}
      http:
        paths:
          - path: /argo-workflows
            pathType: Prefix
            backend:
              service:
                name: argo-server
                port:
                  name: web
