apiVersion: awsblueprints.io/v1alpha1
kind: ObjectStorage
metadata:
  name: test-s3-composition
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      s3.awsblueprints.io/configuration: standard
  writeConnectionSecretToRef:
    name: test-s3-composition-connection
  resourceConfig:
    providerConfigName: default
    region: us-west-2
    name: crossplane-v2-test-bucket
    tags:
      - key: Environment
        value: test
      - key: Purpose
        value: crossplane-v2-composition-test