# Crossplane PodIdentityAssociation for ExternalDNS
# Links the IAM role to the external-dns-sa service account in kube-system
apiVersion: eks.aws.upbound.io/v1beta1
kind: PodIdentityAssociation
metadata:
  name: external-dns-pod-identity
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        platform.gitops.io/cluster-name: hub
    namespace: kube-system
    serviceAccount: external-dns-sa
    roleArnSelector:
      matchLabels:
        platform.gitops.io/role: external-dns-pod-identity
    region: us-west-2
  providerConfigRef:
    name: default
