apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates Amazon RDS Database with CrossPlane
  name: db-cluster-rds
  title: Creates an Amazon RDS Database
spec:
  owner: guest
  type: service
  parameters:
    - properties:
        name:
          title: Application Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        namespace:
          default: flux-system
          title: namespace within the kubernetes cluster to deploy this
          type: string
        region:
          title: aws region
          type: string
        subnetIds:
          title: Subnet IDs
          description: ID of subnets for rds cluster
          type: array
          items:
            type: string
      title: Configuration Options
      required:
        - name
        - region
        - subnetIds
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/system-info
    - action: fetch:template
      id: fetch-base
      input:
        url: ./skeleton/
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          region: ${{ parameters.region }}
          repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}
          subnetIds: ${{parameters.subnetIds}}
      name: Fetch Base
    - id: publish
      name: Publishing to GitLab repository
      action: publish:gitlab
      input:
        # Hard coded value for this demo purposes only.
        repoUrl: ${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}?repo=${{parameters.name}}&owner=${{ steps['fetchSystem'].output.entity.spec.gituser }}
        defaultBranch: main
    - id: create-argocd-project
      name: Create ArgoCD Project
      action: kube:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: AppProject
          metadata:
            name: ${{parameters.name}}-project
            namespace: argocd
          spec:
            description: Project for ${{parameters.name}} RDS cluster
            sourceNamespaces:
            - argocd
            sourceRepos:
            - https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.name}}.git
            destinations:
            - namespace: ${{parameters.namespace}}
              name: ${{ steps['fetchSystem'].output.entity.spec.hub_cluster_name }}
            clusterResourceWhitelist:
            - group: '*'
              kind: '*'
            namespaceResourceWhitelist:
            - group: '*'
              kind: '*'
    - id: create-argocd-app
      name: Create ArgoCD App
      action: kube:apply
      input:
        namespaced: true
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{parameters.name}}
            namespace: argocd
            labels:
              backstage-name: ${{parameters.name}}
            finalizers:
            - resources-finalizer.argocd.argoproj.io
          spec:
            project: ${{parameters.name}}-project
            destination:
              namespace: ${{parameters.namespace}}
              name: ${{ steps['fetchSystem'].output.entity.spec.hub_cluster_name }}
            source:
              repoURL: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.name}}.git
              targetRevision: HEAD
              path: manifests
            syncPolicy:
              automated:
                allowEmpty: true
                prune: false
                selfHeal: true
              retry:
                backoff:
                  duration: 5s
                  factor: 2
                  maxDuration: 5m
                limit: 10
              syncOptions:
              - CreateNamespace=false
              - FailOnSharedResource=true
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: https://${{ steps['fetchSystem'].output.entity.spec.gitlab_hostname }}/${{ steps['fetchSystem'].output.entity.spec.gituser }}/${{parameters.name}}/-/blob/main
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
