apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-prod
  namespace: argocd
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.17.1
    helm:
      releaseName: crossplane
      values: |
        args:
          - --enable-environment-configs
  destination:
    name: 'prod-cluster'
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
