# AWS configuration for IRSA integration
aws:
  irsaRoleArn: ""

# Provider configuration
providers:
  aws:
    enabled: true
    familyVersion: "v2.5.2"
    s3Version: "v2.5.2"
    dynamodbVersion: "v2.5.2"
    apigatewayv2Version: "v2.5.2"
    eksVersion: "v2.5.2"
    ec2Version: "v2.5.2"
    iamVersion: "v2.5.2"
    lambdaVersion: "v2.5.2"
    rdsVersion: "v2.5.2"
    runtimeConfigRef: "aws-irsa-drc"
    # Default resources for all providers
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

compositions:
  enabled: true

functions:
  patchAndTransform:
    enabled: true
    package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.8.2
  environmentConfigs:
    enabled: true
    package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.6.0

namespace: crossplane-system
