apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela-dev
  namespace: argocd
spec:
  project: default
  destination:
    namespace: vela-system
    name: dev-cluster
  source:
    repoURL: ${GITHUB_URL}
    targetRevision: ${GITHUB_BRANCH}
    path: deployment/addons/kubevela
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
