# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rds-postgresql.awsblueprints.io
  labels:
    awsblueprints.io/provider: aws
    awsblueprints.io/environment: dev
    awsblueprints.io/createDBSubnetGroup: "true"
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XRelationalDatabase
  mode: Pipeline
  pipeline:
    - step: rds-resources
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: db-subnet-group
            base:
              apiVersion: rds.aws.upbound.io/v1beta1
              kind: SubnetGroup
              spec:
                forProvider:
                  description: "rds-postgres"
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.deletionPolicy
                toFieldPath: spec.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
              - fromFieldPath: spec.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
              - fromFieldPath: "spec.subnetIds"
                toFieldPath: spec.forProvider.subnetIds
              - fromFieldPath: "metadata.uid"
                toFieldPath: "spec.writeConnectionSecretToRef.name"
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-dbsubnet"
          - name: security-group
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: SecurityGroup
              spec:
                forProvider:
                  description: "rds-postgres-sg"
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
              - fromFieldPath: "spec.vpcId"
                toFieldPath: "spec.forProvider.vpcId"
          - name: db-instance
            base:
              apiVersion: rds.aws.upbound.io/v1beta3
              kind: Instance
              spec:
                forProvider:
                  applyImmediately: true
                  backupRetentionPeriod: 3
                  dbSubnetGroupNameSelector:
                    matchControllerRef: true
                  instanceClass: db.t4g.small
                  username: root
                  passwordSecretRef:
                    key: password
                    name: test-postgres-password
                    namespace: crossplane-system
                  engine: postgres
                  engineVersion: "14.11"
                  skipFinalSnapshot: true
                  storageEncrypted: true
                  storageType: gp3
                  publiclyAccessible: false
                  vpcSecurityGroupIdSelector:
                    matchControllerRef: true
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.deletionPolicy
                toFieldPath: spec.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.region
                toFieldPath: spec.forProvider.region
              - fromFieldPath: spec.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: spec.resourceConfig.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
              - fromFieldPath: "metadata.uid"
                toFieldPath: "spec.writeConnectionSecretToRef.name"
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-postgresql"
              - fromFieldPath: "spec.storageGB"
                toFieldPath: "spec.forProvider.allocatedStorage"
              - fromFieldPath: "spec.engineVersion"
                toFieldPath: "spec.forProvider.engineVersion"
              - fromFieldPath: "spec.databaseName"
                toFieldPath: "spec.forProvider.dbName"
            connectionDetails:
              - name: username
                type: FromConnectionSecretKey
                fromConnectionSecretKey: username
              - name: password
                type: FromConnectionSecretKey
                fromConnectionSecretKey: password
              - name: endpoint
                type: FromConnectionSecretKey
                fromConnectionSecretKey: endpoint
              - name: port
                type: FromConnectionSecretKey
                fromConnectionSecretKey: port

